version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
      target: builder  # Use the builder stage for development
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - AIDER_API_KEY=test-key
      - AIDER_GITHUB_TOKEN=test-token
    command: uvicorn aider.api.main:app --host 0.0.0.0 --port 8000 --reload

  test:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
      target: builder
    volumes:
      - .:/app
    environment:
      - AIDER_API_KEY=test-key
      - AIDER_GITHUB_TOKEN=test-token
    command: pytest tests/api -v